name: TF Test Site
favicon: null
layout_spectrum: 0.7705440260469913
typography_spectrum: 0.857401184272021
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9781602001748979
  lightness: 0.269820564892143
  saturation: 0.8696385272778571
  rhythmicContrast: 0.48340411111712456
purpose: []
